name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v1
#       with:
#         python-version: 3.8
    
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pyyaml 
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
    
    - name: Check python version
      run: |
        python --version
        node --version
        npm --version
        
    - name: Check python version
      run: |
        npm i -g serverless
        serverless -v
